version: "3"

services:
  nginx:
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/mnaimi/data/html:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"

  wordpress:
    build:
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/mnaimi/data/html:/var/www/html
    depends_on:
      - mariadb
    # ports:
    #   - "443:443"
    restart: always

  mariadb:
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/mnaimi/data/mariadb:/var/lib/mariadb
    # ports:
    #   - "443:443"
    restart: always

