version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/data/wordpress:/var/www/wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/data/wordpress:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure
    # volumes:
    #   - /Users/mnaimi/data/mariadb:/var/lib/mysql

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure

  cadvisor:
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    networks:
      - inception-network
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure

  redis:
      container_name: redis
      build:
        context: ./requirements/bonus/redis
        dockerfile: Dockerfile
      depends_on:
        - wordpress
      ports:
        - "6379:6379"
      networks:
        - inception-network
      env_file:
        - .env
      restart: on-failure

  static-website:
    container_name: static-website
    build:
      context: ./requirements/bonus/static-website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    networks:
      - inception-network
    env_file:
      - .env
    restart: on-failure

networks:
  inception-network:
    driver: bridge
