version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - internal
      - external
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/mnaimi/data/html:/var/www/html
    depends_on:
      - mariadb
    networks:
      - internal
    env_file:
      - .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/mnaimi/data/mariadb:/var/lib/mariadb
    networks:
      - internal
    env_file:
      - .env
    restart: on-failure

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
    external: true
