version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/Desktop/data/wordpress:/var/www/wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/Desktop/data/wordpress:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    # volumes:
    #   - /Users/mnaimi/Desktop/data/mariadb

networks:
  inception:
    driver: bridge
