version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/data/wordpress:/var/www/wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/data/wordpress:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /Users/mnaimi/data/mariadb:/var/lib/mysql

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: on-failure

  # redis:
  #     container_name: redis
  #     build:
  #       context: ./requirements/bonus/redis
  #       dockerfile: Dockerfile
  #     depends_on:
  #       - mariadb
  #     networks:
  #       - inception
  #     env_file:
  #       - .env
  #     restart: on-failure
  #     volumes:
  #       -

  # ftp:
  #   container_name: ftp
  #   build:
  #     context: ./requirements/bonus/ftp
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  #   restart: on-failure
  #   volumes:
  #     -
   

networks:
  inception:
    driver: bridge
