# Build the NGINX container


# Build the Wordpres/PHP-FPM container


# Build the MariaDB container


# Launch the NGINX container


# Launch the Wordpres/PHP-FPM container


# Launch the MariaDB container

